#!/bin/sh


#PWE Deps
PWE_HOME=$(/usr/bin/pwe-env -home)
PWE_CP=$(/usr/bin/pwe-env -cp)
CP=""
RUN="NO"

# Deps from the project

case "$*" in
(*-run*) RUN="YES";;
esac

if [[ $RUN == "YES" ]]; then

    UPDATE_DEPS="YES"

    # the -fast option will specify that we should not try to recompute deps

    # the -nocompile disables PwE from compiling before it runs (only used in development)

    while getopts ":a" opt; do
	case $opt in
	    a)
		UPDATE_DEPS="NO"
		;;
	esac
    done

    if [[ $UPDATE_DEPS == "YES" ]]; then
	mvn dependency:copy-dependencies
	if [ $? -ne 0 ]; then
            exit $?
	fi
    else
	echo "Running PwE application without updating dependencies..."
    fi


    # update the package

    mvn package
    if [ $? -ne 0 ]; then
        exit $?
    fi

    # Add everything this depends on to the classpath...

    CP=""

    for jar in "target/dependency"/*.jar
    do
	CP="$jar:${CP}"
    done


    for jar in "target"/*.jar
    do
	CP="$jar:${CP}"
    done

fi


eval "java"  -cp "${PWE_CP}:${CP}" PwEMain -nocompile "$@"
