#!/bin/sh


VERILY_HOME=$1

cd $VERILY_HOME

CP=""

for jar in "lib"/*.jar
do
    CP="${VERILY_HOME}/$jar:${CP}"
done



cat >/usr/bin/verily-env <<EOF
#!/bin/sh


VERILY_HOME="$1"
VERILY_CP="$CP"

if [[ \$1 == "-cp" ]]; then
    # display the classpath
    echo "\${VERILY_CP}"
fi

if [[ \$1 == "-home" ]]; then
    echo "\${VERILY_HOME}"
fi





EOF

chmod +x /usr/bin/verily-env

rm /usr/bin/verily

ln -s "$1/verily" /usr/bin/verily
