#+TITLE: Verily Framework Manual 
#+AUTHOR: John L. Singleton



* Introduction

Verily is a web framework for Java that supports the development of verified applications. 


* Quick Answers to Common Questions

** What kind of applications is Verily suited for?

Any kind of application! Well, strictly speaking Verily is very good at creating Web-based applications that benefit from reliable behavior. Specifically, dynamic web applications. Verily isn't especially well-suited from creating sites with a lot of static content (though it is possible). 

Verily is good for creating:
- [[http://en.wikipedia.org/wiki/Single-page_application][Single Page Applications]] (SPA), typically built with a Javascript framework like [[http://backbonejs.org/][Backbone.js]].
- Traditional web-based applications wherein a given web page is rendered and refreshed using things like HTML forms to deliver requests to the server. 

* Papers and Presentations 

Below you can find a list of papers and presentations related to Verily. 

* Quickstart


* Verily's View of Web Applications 



* Methods

* Routers

* Responses 



